# Generated by Django 6.0.8 on 2026-09-02 21:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tap_grid", "0002_entitytype_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalZizmorFinding",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "audit_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("audit_url", models.CharField(blank=True, default="", max_length=512)),
                (
                    "severity",
                    models.CharField(blank=True, db_index=True, default="Unknown", max_length=16),
                ),
                (
                    "confidence",
                    models.CharField(blank=True, db_index=True, default="Unknown", max_length=16),
                ),
                (
                    "persona",
                    models.CharField(blank=True, default="Regular", max_length=16),
                ),
                (
                    "scanner_version",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("location", models.JSONField(blank=True, default=dict)),
                ("fixes", models.JSONField(blank=True, default=list)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("known_since", models.DateTimeField(blank=True, null=True)),
                (
                    "observed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical zizmor finding",
                "verbose_name_plural": "historical zizmor findings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalZizmorRun",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "scanner_version",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "persona",
                    models.CharField(blank=True, default="Auditor", max_length=16),
                ),
                ("audit_set", models.JSONField(blank=True, default=list)),
                ("skipped_audits", models.JSONField(blank=True, default=list)),
                (
                    "outcome",
                    models.CharField(blank=True, db_index=True, default="running", max_length=16),
                ),
                (
                    "source_collection_job",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("repositories_scanned", models.IntegerField(default=0)),
                ("workflows_evaluated", models.IntegerField(default=0)),
                ("workflows_parse_failed", models.IntegerField(default=0)),
                ("workflows_skipped", models.IntegerField(default=0)),
                ("workflows_no_yaml", models.IntegerField(default=0)),
                ("counts_by_audit", models.JSONField(blank=True, default=dict)),
                ("counts_by_severity", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tap_grid.entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical zizmor run",
                "verbose_name_plural": "historical zizmor runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ZizmorFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "audit_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("audit_url", models.CharField(blank=True, default="", max_length=512)),
                (
                    "severity",
                    models.CharField(blank=True, db_index=True, default="Unknown", max_length=16),
                ),
                (
                    "confidence",
                    models.CharField(blank=True, db_index=True, default="Unknown", max_length=16),
                ),
                (
                    "persona",
                    models.CharField(blank=True, default="Regular", max_length=16),
                ),
                (
                    "scanner_version",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("location", models.JSONField(blank=True, default=dict)),
                ("fixes", models.JSONField(blank=True, default=list)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("known_since", models.DateTimeField(blank=True, null=True)),
                (
                    "observed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "zizmor__finding",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZizmorRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                (
                    "scanner_version",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "persona",
                    models.CharField(blank=True, default="Auditor", max_length=16),
                ),
                ("audit_set", models.JSONField(blank=True, default=list)),
                ("skipped_audits", models.JSONField(blank=True, default=list)),
                (
                    "outcome",
                    models.CharField(blank=True, db_index=True, default="running", max_length=16),
                ),
                (
                    "source_collection_job",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("repositories_scanned", models.IntegerField(default=0)),
                ("workflows_evaluated", models.IntegerField(default=0)),
                ("workflows_parse_failed", models.IntegerField(default=0)),
                ("workflows_skipped", models.IntegerField(default=0)),
                ("workflows_no_yaml", models.IntegerField(default=0)),
                ("counts_by_audit", models.JSONField(blank=True, default=dict)),
                ("counts_by_severity", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="tap_grid.entity",
                    ),
                ),
            ],
            options={
                "db_table": "zizmor__run",
                "abstract": False,
            },
        ),
    ]
